version: "3.9"  
services:
  postgres:
    image: postgres:14-alpine3.15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: auth_svc
  auth_svc:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_URL=postgres://root:secret@postgres:5432/auth_svc